config/routes.rb
Rails.application.routes.draw do

  get 'feedbacks/about'

  resources :feedbacks


  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/' 

  get '/about' => 'spree/home#about', :as => 'about'
  get '/contact' => 'spree/home#contact', :as => 'contact'

          # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def new
  	@feedback = Feedback.new
  end

  def create
  	@feedback = Feedback.new params[feedback_params]
  	@feedback.save
      if @feedback.save
  		  redirect_to spree_url
  	end
  end

  def about
  end

  private

  def feedback_params
  	params.require(:feedback).permit(:title, :text, :mail)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/about.html.erb
<h1>Feedbacks#about</h1>
<p>Find me in app/views/feedbacks/about.html.erb</p>

app/views/feedbacks/create.html.erb
<h1>Feedbacks#create</h1>
<p>Find me in app/views/feedbacks/create.html.erb</p>

app/views/feedbacks/new.html.erb
<%= form_for :feedback ,url: feedbacks_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

    <p>
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </p>

 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/spree/address/_form.html.erb
<% address_id = address_type.chars.first %>

<div class="inner" data-hook=<%="#{address_type}_inner" %>>
  <p class="form-group" id=<%="#{address_id}firstname" %>>
    <%= form.label :firstname do %>
      <%= Spree.t(:first_name) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :firstname, class: 'form-control required' %>
  </p>
  <p class="form-group" id=<%="#{address_id}lastname" %>>
    <%= form.label :lastname do %>
      <%= Spree.t(:last_name) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :lastname, class: 'form-control required' %>
  </p>
  <% if Spree::Config[:company] %>
    <p class="form-group" id=<%="#{address_id}company" %>>
      <%= form.label :company, Spree.t(:company) %>
      <%= form.text_field :company, class: 'form-control' %>
    </p>
  <% end %>
  <p class="form-group" id=<%="#{address_id}address1" %>>
    <%= form.label :address1 do %>
      <%= Spree.t(:street_address) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :address1, class: 'form-control  required' %>
  </p>
  <p class="form-group" id=<%="#{address_id}address2" %>>
    <%= form.label :address2, Spree.t(:street_address_2) %>
    <%= form.text_field :address2, class: 'form-control' %>
  </p>
  <p class="form-group" id=<%="#{address_id}city" %>>
    <%= form.label :city do %>
      <%= Spree.t(:city) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :city, class: 'form-control required' %>
  </p>
  <p class="form-group" id=<%="#{address_id}country" %>>
    <%= form.label :country_id do %>
      <%= Spree.t(:country) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <span id=<%="#{address_id}country-selection" %>>
      <%= form.collection_select :country_id, available_countries, :id, :name, {}, {class: 'form-control required'} %>
    </span>
  </p>

  <% if Spree::Config[:address_requires_state] %>
    <p class="form-group" id=<%="#{address_id}state" %>>
      <% have_states = !address.country.states.empty? %>
      <%= form.label :state do %>
        <%= Spree.t(:state) %><abbr class='required' title="required" id=<%="#{address_id}state-required"%>>*</abbr>
      <% end %>

      <%== state_elements = [
         form.collection_select(:state_id, address.country.states,
                            :id, :name,
                            {include_blank: true},
                            {class: have_states ? 'form-control required' : 'form-control hidden',
                            disabled: !have_states}) +
         form.text_field(:state_name,
                            class: !have_states ? 'form-control required' : 'form-control hidden',
                            disabled: have_states)
         ].join.gsub('"', "'").gsub("\n", "")
      %>
    </p>
      <noscript>
        <%= form.text_field :state_name, class: 'form-control required' %>
      </noscript>
  <% end %>

  <p class="form-group" id=<%="#{address_id}zipcode" %>>
    <%= form.label :zipcode do %>
      <%= Spree.t(:zip) %><% if address.require_zipcode? %><abbr class="required" title="required">*</abbr><% end %>
    <% end %>
    <%= form.text_field :zipcode, class: "form-control #{'required' if address.require_zipcode?}" %>
  </p>
  <p class="form-group" id=<%="#{address_id}phone" %>>
    <%= form.label :phone do %>
      <%= Spree.t(:phone) %><% if address.require_phone? %><abbr class="required" title="required">*</abbr><% end %>
    <% end %>
    <%= form.phone_field :phone, class: "form-control #{'required' if address.require_phone?}" %>
  </p>
  <% if Spree::Config[:alternative_shipping_phone] %>
    <p class="form-group" id=<%="#{address_id}altphone" %>>
      <%= form.label :alternative_phone, Spree.t(:alternative_phone) %>
      <%= form.phone_field :alternative_phone, class: 'form-control' %>
    </p>
  <% end %>
</div>

app/views/spree/checkout/_address.html.erb
<div class="row">
  <div class="col-sm-6" data-hook="billing_fieldset_wrapper">
    <div class="panel panel-default" id="billing" data-hook>
      <%= form.fields_for :bill_address do |bill_form| %>
        <div class="panel-heading">
          <h3 class="panel-title"><%= Spree.t(:billing_address) %></h3>
        </div>
        <div class="panel-body">
          <%= render partial: 'spree/address/form', locals: { form: bill_form, address_type: 'billing', address: @order.bill_address } %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-sm-6" data-hook="shipping_fieldset_wrapper">
    <div class="panel panel-default" id="shipping" data-hook>
      <%= form.fields_for :ship_address do |ship_form| %>
        <div class="panel-heading">
          <h3 class="panel-title"><%= Spree.t(:shipping_address) %></h3>
        </div>
        <div class="panel-body">
          <p class="field checkbox" data-hook="use_billing">
            <%= label_tag :order_use_billing, id: 'use_billing' do %>
              <%= check_box_tag 'order[use_billing]', '1', @order.shipping_eq_billing_address? %>
              <%= Spree.t(:use_billing_address) %>
            <% end %>
          </p>
          <%= render partial: 'spree/address/form', locals: { form: ship_form, address_type: 'shipping', address: @order.ship_address } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="well text-right form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success' %>
  <% if try_spree_current_user %>
    <span data-hook="save_user_address">
      &nbsp; &nbsp;
      <%= check_box_tag 'save_user_address', '1', try_spree_current_user.respond_to?(:persist_order_address) %>
      <%= label_tag :save_user_address, Spree.t(:save_my_address) %>
    </span>
  <% end %>
</div>

app/views/spree/checkout/_confirm.html.erb
<div class="panel panel-default" id="order_details" data-hook>
  <div class="panel-heading">
    <h3 class="panel-title"><%= Spree.t(:confirm) %></h3>
  </div>
  <div class="panel-body">
    <%= render partial: 'spree/shared/order_details', locals: { order: @order } %>
  </div>
</div>

<div class="well text-right form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:place_order), class: 'btn btn-lg btn-success' %>
  <script>Spree.disableSaveOnClick();</script>
</div>

app/views/spree/checkout/_delivery.html.erb
<div class="panel panel-default" id='shipping_method' data-hook>
  <div class="panel-heading">
    <h3 class="panel-title"><%= Spree.t(:delivery) %></h3>
  </div>
  <div class="panel-body" data-hook="shipping_method_inner">
    <div id="methods">
      <%= form.fields_for :shipments do |ship_form| %>
        <div class="shipment">
          <h4 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:package_from) %>
            <strong class="stock-location-name" data-hook="stock-location-name"><%= ship_form.object.stock_location.name %></strong>
          </h4>

          <table class="table stock-contents" data-hook="stock-contents">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <tr class="active">
                <th></th>
                <th align='left'><%= Spree.t(:item) %></th>
                <th><%= Spree.t(:qty) %></th>
                <th><%= Spree.t(:price) %></th>
              </tr>
            </thead>
            <tbody>
              <% ship_form.object.manifest.each do |item| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(item.variant) %></td>
                  <td class="item-name"><%= item.variant.name %></td>
                  <td class="item-qty"><%= item.quantity %></td>
                  <td class="item-price"><%= display_price(item.variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <h4 class="stock-shipping-method-title"><%= Spree.t(:shipping_method) %></h4>
          <ul class="list-group shipping-methods">
            <% ship_form.object.shipping_rates.each do |rate| %>
              <li class="list-group-item shipping-method">
                <label>
                  <%= ship_form.radio_button :selected_shipping_rate_id, rate.id, data: { behavior: 'shipping-method-selector', cost: rate.display_cost } %>
                  <span class="rate-name"><%= rate.name %></span>
                  <span class="badge rate-cost"><%= rate.display_cost %></span>
                </label>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <% if @differentiator.try(:missing?) %>
        <div class="shipment unshippable">
          <h3 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:unshippable_items) %>
          </h3>
          <table class="table stock-contents" data-hook="stock-missing">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= Spree.t(:item) %></th>
              <th><%= Spree.t(:qty) %></th>
              <th><%= Spree.t(:price) %></th>
            </thead>
            <tbody>
              <% @differentiator.missing.each do |variant, quantity| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(variant) %></td>
                  <td class="item-name"><%= variant.name %></td>
                  <td class="item-qty"><%= quantity %></td>
                  <td class="item-price"><%= display_price(variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
    <% if Spree::Config[:shipping_instructions] %>
      <p id="minstrs" data-hook>
        <h4><%= Spree.t(:shipping_instructions) %></h4>
        <%= form.text_area :special_instructions, cols: 40, rows: 4, class: "form-control" %>
      </p>
    <% end %>
  </div>
</div>

<br />

<div class="well text-right form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success' %>
</div>

<%= javascript_include_tag 'spree/frontend/checkout/shipment' %>

app/views/spree/checkout/_payment.html.erb
<div class="panel panel-default" id="payment" data-hook>
  <div class="panel-heading">
    <h3 class="panel-title"><%= Spree.t(:payment_information) %></h3>
  </div>
  <div class="panel-body" data-hook="checkout_payment_step">
    <% if @payment_sources.present? %>
      <div class="card_options">
        <%= radio_button_tag 'use_existing_card', 'yes', true %>
        <label for="use_existing_card_yes">
          <%= Spree.t(:use_existing_cc) %>
        </label>
        <%= radio_button_tag 'use_existing_card', 'no' %>
        <label for="use_existing_card_no">
          <%= Spree.t(:use_new_cc_or_payment_method) %>
        </label>
      </div>

      <div id="existing_cards">
        <p class="form-group" data-hook="existing_cards">
          <table class="existing-credit-card-list">
            <tbody>
              <% @payment_sources.each do |card| %>
                <tr id="<%= dom_id(card,'spree')%>" class="<%= cycle('even', 'odd') %>">
                  <td><%= card.name %></td>
                  <td><%= card.display_number %></td>
                  <td><%= card.month %> / <%= card.year %></td>
                  <td>
                    <%= radio_button_tag "order[existing_card]", card.id, (card == @payment_sources.first), { class: "existing-cc-radio" }  %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </p>
      </div>
    <% end %>

    <%= render partial: 'spree/checkout/payment/storecredit' %>

    <ul class="list-group" id="payment-method-fields" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li class="list-group-item">
          <label>
            <%= radio_button_tag "order[payments_attributes][][payment_method_id]", method.id, method == @order.available_payment_methods.first %>
            <%= Spree.t(method.name, scope: :payment_methods, default: method.name) %>
          </label>
        </li>
      <% end %>
    </ul>

    <ul class="nav" id="payment-methods" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li id="payment_method_<%= method.id %>" class="<%= 'last' if method == @order.available_payment_methods.last %>" data-hook>
          <fieldset>
            <%= render partial: "spree/checkout/payment/#{method.method_type}", locals: { payment_method: method } %>
          </fieldset>
        </li>
      <% end %>
    </ul>

    <p class='field' data-hook='coupon_code'>
      <%= form.label :coupon_code %>
      <%= form.text_field :coupon_code, class: 'form-control' %>
    </p>
  </div>
</div>

<div class="well text-right form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success primary' %>
  <script>Spree.disableSaveOnClick();</script>
</div>

app/views/spree/checkout/_summary.html.erb
<h3><%= Spree.t(:order_summary) %></h3>

<table class="table" data-hook="order_summary">
  <tbody>
    <tr data-hook="item_total">
      <td><strong><%= Spree.t(:item_total) %>:</strong></td>
      <td><strong><%= order.display_item_total.to_html %></strong></td>
    </tr>

    <% if order.line_item_adjustments.nonzero.exists? %>
      <tbody data-hook="order_details_promotion_adjustments">
        <% order.line_item_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
          <tr class="total">
            <td><%= label %></td>
            <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>

    <tbody data-hook="order_details_tax_adjustments">
      <% order.all_adjustments.nonzero.tax.eligible.group_by(&:label).each do |label, adjustments| %>
        <tr class="total">
          <td><%= label %></td>
          <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
        </tr>
      <% end %>
    </tbody>

    <% if order.passed_checkout_step?("address") && order.shipments.any? %>
      <tr data-hook="shipping_total">
        <td><%= Spree.t(:shipping_total) %>:</td>
        <td data-hook='shipping-total' data-currency=<%= Money::Currency.find(order.currency).symbol %>><%= Spree::Money.new(order.shipments.to_a.sum(&:cost), currency: order.currency).to_html %></td>
      </tr>

      <% if order.shipment_adjustments.nonzero.exists? %>
        <tbody data-hook="order_details_shipment_promotion_adjustments">
          <% order.shipment_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
            <tr class="total">
              <td><%= label %>:</td>
              <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    <% end %>

    <% if order.adjustments.nonzero.eligible.exists? %>
      <tbody id="summary-order-charges" data-hook>
        <% order.adjustments.nonzero.eligible.each do |adjustment| %>
        <% next if (adjustment.source_type == 'Spree::TaxRate') and (adjustment.amount == 0) %>
          <tr class="total">
            <td><%= adjustment.label %>:</td>
            <td><%= adjustment.display_amount.to_html %></td>
          </tr>
        <% end %>
      </tbody>
    <% end %>

    <tr data-hook="order_total">
      <td><strong><%= Spree.t(:order_total) %>:</strong></td>
      <td><strong><span id='summary-order-total' class="lead text-primary" data-currency=<%= Money::Currency.find(order.currency).symbol %>><%= order.display_total.to_html %></span></strong></td>
    </tr>

    <% if order.using_store_credit? %>
      <tr data-hook="order_details_store_credit">
        <td><strong><%= Spree.t(:store_credit_name) %>:</strong></td>
        <td><span id='summary-store-credit'><%= order.display_total_applied_store_credit.to_html %></span></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/checkout/edit.html.erb
<% @body_id = 'checkout-page' %>
<% content_for :google_analytics do %>
  <%= render partial: 'spree/shared/google_checkout.js', locals: { order: @order, step_number: (@order.checkout_steps.index(@order.state) + 1) } %>
<% end %>

<div id="checkout" data-hook>
  <%= render partial: 'spree/shared/error_messages', locals: { target: @order } %>

  <div class="row" data-hook="checkout_header">
    <div class="col-sm-3">
      <h1 data-hook="checkout_title"><%= Spree.t(:checkout) %></h1>
    </div>
    <div class="col-sm-9" data-hook="checkout_progress">
      <%= checkout_progress %>
    </div>
  </div>

  <div class="row" data-hook="checkout_content">
    <div class="<%= if @order.state != 'confirm' then 'col-md-9' else 'col-md-12' end %>" data-hook="checkout_form_wrapper">
      <%= form_for @order, url: update_checkout_path(@order.state), html: { id: "checkout_form_#{@order.state}" } do |form| %>
        <% if @order.state == 'address' || !@order.email? %>
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="form-group">
                <%= form.label :email %>
                <%= form.text_field :email, class: 'form-control' %>
              </div>
            </div>
          </div>
        <% end %>
        <%= form.hidden_field :state_lock_version %>
        <%= render @order.state, form: form %>
      <% end %>
    </div>
    <% if @order.state != 'confirm' %>
      <div id="checkout-summary" data-hook="checkout_summary_box" class="col-md-3">
        <%= render partial: 'summary', locals: { order: @order } %>
      </div>
    <% end %>
  </div>
</div>

<script>
  Spree.current_order_id = "<%= @order.number %>"
  Spree.current_order_token = "<%= @order.guest_token %>"
</script>

<% if I18n.locale != :en %>
  <%= javascript_include_tag 'jquery.validate/localization/messages_' + I18n.locale.to_s.downcase.gsub('-', '') %>
<% end %>

app/views/spree/checkout/payment/_gateway.html.erb
<div class="well clearfix">
  <%= image_tag 'credit_cards/credit_card.gif', id: 'credit-card-image', class: 'pull-right', width: '170', height: '28' %>
  <% param_prefix = "payment_source[#{payment_method.id}]" %>

  <p class="field">
    <%= label_tag "name_on_card_#{payment_method.id}" do %>
      <%= Spree.t(:name_on_card) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= text_field_tag "#{param_prefix}[name]", "#{@order.bill_address_firstname} #{@order.bill_address_lastname}", { id: "name_on_card_#{payment_method.id}", class: 'form-control required'} %>
  </p>

  <p class="field" data-hook="card_number">
    <%= label_tag "card_number" do %>
      <%= Spree.t(:card_number) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <% options_hash = Rails.env.production? ? {autocomplete: 'off'} : {} %>
    <%= text_field_tag "#{param_prefix}[number]", '', options_hash.merge(id: 'card_number', class: 'form-control required cardNumber', size: 19, maxlength: 19, autocomplete: "off") %>
    &nbsp;
    <span id="card_type" style="display:none;">
      ( <span id="looks_like" ><%= Spree.t(:card_type_is) %> <span id="type"></span></span>
        <span id="unrecognized"><%= Spree.t(:unrecognized_card_type) %></span>
      )
    </span>
  </p>
  <div class="row">
    <div class="col-md-8 field" data-hook="card_expiration">
      <%= label_tag "card_expiry" do %>
        <%= Spree.t(:expiration) %><abbr class="required" title="required">*</abbr>
      <% end %>
      <%= text_field_tag "#{param_prefix}[expiry]", '', id: 'card_expiry', class: "form-control required cardExpiry", placeholder: "MM / YY" %>
    </div>
    <div class="col-md-4 field" data-hook="card_code">
      <%= label_tag "card_code" do %>
        <%= Spree.t(:card_code) %><abbr class="required" title="required">*</abbr>
      <% end %>
      <%= text_field_tag "#{param_prefix}[verification_value]", '', options_hash.merge(id: 'card_code', class: 'form-control required cardCode', size: 5) %>
      <%= link_to "(#{Spree.t(:what_is_this)})", spree.content_path('cvv'), target: '_blank', "data-hook" => "cvv_link", id: "cvv_link" %>
    </div>
  </div>

  <%= hidden_field_tag "#{param_prefix}[cc_type]", '', id: "cc_type", class: 'ccType' %>
</div>

app/views/spree/checkout/payment/_storecredit.html.erb
<% if @order.using_store_credit? %>
  <div class="alert alert-success text-center" data-hook="checkout_payment_store_credit_success">
    <h3><%= Spree.t('store_credit.applicable_amount', amount: Spree::Money.new(@order.total_applicable_store_credit, { currency: @order.currency })) %></h3>
    <% if @order.covered_by_store_credit? %>
      <p><%= Spree.t('store_credit.remaining_amount', amount: @order.display_store_credit_remaining_after_capture) %></p>
    <% else %>
      <p><%= Spree.t('store_credit.additional_payment_needed', amount: @order.display_order_total_after_store_credit) %></p>
    <% end %>
  </div>

<% elsif @order.could_use_store_credit? %>
  <div class="alert alert-info text-center" data-hook="checkout_payment_store_credit_available">
    <h2><%= Spree.t('store_credit.available_amount', amount: @order.display_total_available_store_credit) %></h2>
    <%= button_tag Spree.t('store_credit.apply'), name: 'apply_store_credit', class: 'continue btn btn-lg btn-primary' %>
  </div>
<% end %>

app/views/spree/home/about.html.erb
<h1> sfddsf</h1>
<h1> sfddsf</h1>
<h1> sfddsf</h1>
<h1> sfddsf</h1>
<h1> sfddsf</h1>
<h1> sfddsf</h1>
<h1> sfddsf</h1>
<h1> sfddsf</h1>
<h1> sfddsf</h1>
<h1> sfddsf</h1>
<h1> sfddsf</h1>
<h1> sfddsf</h1>

app/views/spree/home/contact.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-offset-4 col-md-3">
        	<div class="form-login">
        	<h4>Обратная связь</h4>
				<form name="xc" method="POST" action="http://formspree.io/toryanshop@gmail.com">
				<br>
				  <input type="email" name="email" placeholder="Почта" class="form-control input-sm chat-input">
				  <br>
				  <textarea name="message" class="form-control input-sm chat-input" placeholder="Сообщение"></textarea>
				  <br>
				  <div class="wrapper">
				    <button type="submit" class="btn btn-primary btn-md">Отправить</button>
				  </div>
				</form>
			</div>
		</div>
	</div>
</div>
<br>
<br>
<br>

app/views/spree/home/index.html.erb
<% @body_id = 'home-page' %>
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <%= render partial: 'spree/shared/taxonomies' %>
  </div>
<% end %>

<div data-hook="homepage_products">
  <% cache(cache_key_for_products) do %>
    <%= render partial: 'spree/shared/products', locals: { products: @products } %>
  <% end %>
</div>

app/views/spree/layouts/spree_application.html.erb
<!doctype html>
<!--[if lt IE 7 ]> <html class="ie ie6" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9" lang="<%= I18n.locale %>"> <![endif]-->
<!--[if gt IE 9]><!--><html lang="<%= I18n.locale %>"><!--<![endif]-->
  <head data-hook="inside_head">
    <%= render partial: 'spree/shared/head' %>
    <!--fonts-->
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">

    <!--//fonts-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
  </head>
  <body class="<%= body_class %>" id="<%= @body_id || 'default' %>" data-hook="body">
    <%= render partial: 'spree/shared/google_analytics.js' %>
    <%= render partial: 'spree/shared/header' %>


    <div class="container">
      <div class="row" data-hook>
        <%= breadcrumbs(@taxon) %>

        <%= render partial: 'spree/shared/sidebar' if content_for? :sidebar %>

        <div id="content" class="<%= !content_for?(:sidebar) ? "col-sm-12" : "col-sm-8 col-md-9" %>" data-hook>
          <%= flash_messages %>
          <%= yield %>
        </div>

        <%= yield :templates %>
      </div>
    </div>
    <%= render partial: 'spree/shared/footer' %>
  </body>
</html>

app/views/spree/payments/_payment.html.erb
<% source = payment.source %>

<% if source.is_a?(Spree::CreditCard) %>
  <span class="cc-type">
    <% unless (cc_type = source.cc_type).blank? %>
      <%= image_tag "credit_cards/icons/#{cc_type}.png" %>
    <% end %>
    <% if source.last_digits %>
      <%= Spree.t(:ending_in) %> <%= source.last_digits %>
    <% end %>
  </span>
  <br />
  <span class="full-name"><%= source.name %></span>
<% else %>
  <%= content_tag(:span, payment.payment_method.name) %>
<% end %>

<span class="payment-amount">(<%= payment.display_amount %>)</span>

app/views/spree/products/_promotions.html.erb
<% promotions = @product.possible_promotions %>

<% if promotions.any? %>
  <div id="promotions">
    <h3><%= Spree.t(:promotions) %></h3>
    <% promotions.each do |promotion| %>
    <div class="well well-sm">
      <h4><%= promotion.name %></h4>
      <p><%= promotion.description %></p>
      <% if promotion.products.any? %>
        <ul>
          <% promotion.products.each do |product| %>
            <li><%= link_to product.name, product_path(product) %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/spree/shared/_link_to_cart.html.erb
<%= link_to_cart %>